version: 2
jobs:
  build:
    docker:
      - image: cirrusci/flutter:stable
    steps:
      - checkout
      - run:
          name: Create keystore
          command: echo $KEY_STORE | base64 --decode > /home/cirrus/project/android/keystore.jks

      - run:
          name: Run Flutter doctor
          command: flutter doctor

      - run:
          name: Run the application tests
          command: flutter test

      - run:
          name: Build the Android version
          command: flutter build appbundle

      - store_artifacts:
          path: build/app/outputs/apk/release/app-release.apk